name=EM PM25 Sensor
version=1.0.0
author=chenliang@null-lab.com
maintainer=chenliang@null-lab.com
sentence=EM PM25 Sensor
paragraph==EM PM25 Sensor
category=
url=https://github.com/emakefun-arduino-library/em_pm25_sensor
architectures=avr,esp32
includes=pm25_sensor.h
depends= 